@startuml MoveFromFoundationToTableau
hide empty description 
skinparam linetype polyline

state "**OPEN_GAME**" as OPEN_GAME_INITIAL
state "**OPEN_GAME**" as OPEN_GAME_FINAL

state "**ShowBoard**" as ShowBoard
state c <<choice>> 

note right of c
  Selected card matches the following requirements:
  - Is an King, **or**
  - Is one lower than top card
     **and** different color of a destination Tableau pile
end note

state "." as A
state "." as B
state "." as C
state "." as D
state "." as E
state "." as F
state "." as G

OPEN_GAME_INITIAL -down-> A : Player selects Move\nfrom Foundation To Tableau
A -down-> B : System request to select Card from Foundation
B -down-> C : Player selects Card
C -down-> D : System request to select Tableau destination pile
D -down-> E : Player selects Tableau destination pile
E -down-> c : [Is valid movement?]
c -down-> G : [True]
c -left-> F : [False] 

G -down-> ShowBoard
ShowBoard -down-> OPEN_GAME_FINAL
F -down-> ShowBoard : System shows error

@enduml