@startuml Player Moves Card From Waste to Foundation
hide empty description 

state "**OPEN_GAME**" as OPEN_GAME_INITIAL
state "**OPEN_GAME**" as OPEN_GAME_FINAL
state "**CLOSED_GAME**" as CLOSED_GAME
state "**ShowBoard**" as ShowBoard
state c <<choice>> 
state d <<choice>> 

note right of c
   Is valid movement?
end note

note left of d
  Is Foundation complete?
end note

state "." as A
state "." as B

OPEN_GAME_INITIAL -down-> c : Player select Move from Waste To Foundation
A -down-> d 
c -down-> A : [True]
d -down-> ShowBoard : [False]
d -down-> CLOSED_GAME : System informs\n about game completed
c -right-> B
B -right-> ShowBoard : System informs\nabout Error
ShowBoard -down-> OPEN_GAME_FINAL

A -right[hidden]-> B

@enduml

