@startuml RestartGame

hide empty description

state c <<choice>>
state "**OPEN_GAME**" as OPEN_GAME_INITIAL
state "**OPEN_GAME**" as OPEN_GAME_FINAL
state "**StartGame**" as START_GAME
state "." as A

OPEN_GAME_INITIAL --> A : The Player request to restart game
A --> c : System asks for confirmation
c --> START_GAME : [confirmed]
c --> OPEN_GAME_FINAL : [!confirmed]
START_GAME --> OPEN_GAME_FINAL

@enduml