@startuml
mix_actor Player

	package views {
		class MenuView
		class ErrorView
		class GameView
		class BoardView

		GameView *--> BoardView
		note on link: showBoard()
		
		GameView *--> MenuView
	}   

	package controllers {
		class FlipThreeCardsFromStock  
	}

	package models {
		class Game
		class Card
		class Stock
		class Waste
		Stock *--> Card
		Waste *--> Card
		Game *-->Waste
		Game *-->Stock
	}


	Player -right-> MenuView
	note on link: Select Stock\


	FlipThreeCardsFromStock -down-> GameView
	note on link: showBoard()
	FlipThreeCardsFromStock -down-> Game
	note on link: isStockEmpty()\nisWasteEmpty()\npopCardFromStock()\nputCardInWaste(card)\nputWasteInStock()

	FlipThreeCardsFromStock  -down-> ErrorView
	note on link: showError()
@enduml
