@startuml UCAnalysis_MoveFromTableauToFoundation

mix_actor Player

package views {
    class MenuView
    class GameCompleteView
    class ErrorView
    class GameView
    class BoardView

    GameView *--> BoardView
    GameView *--> MenuView
}

package controllers {
    class PlayController
    class MoveFromTableauToFoundation
    PlayController *-right-> MoveFromTableauToFoundation
}

package models {
    class Game
    class Card
    class Tableau
    class Foundation
    class Pile

    Game --> Tableau
    Game --> Foundation 
    Tableau ..> Pile
    Pile ..> Card
    Foundation ..> Card
    Tableau -right[hidden]-> Foundation
}

Player -up-> GameView
note on link : Select action\
\nSelect Card\
\nSelect destination Pile

MoveFromTableauToFoundation --> Game 
note on link: getFromTableauToFoundation(card, dPile)

MoveFromTableauToFoundation --> ErrorView 
note on link: showError()

MoveFromTableauToFoundation --> GameView 
note on link: show()

MoveFromTableauToFoundation --> GameCompleteView 
note on link: show()

PlayController --> GameView
note on link: readAction()
@enduml