@startuml Analysis Random Movement
mix_actor Player

package views {
    class GameView
    class ErrorView
}

Player -right-> GameView
note on link: Selects Exit

package controllers {
    class PlayController
    class RandomMovementController{
        -generateRandomAction()
    }
    PlayController *-left-> RandomMovementController
}

package models{
    class Game
}

PlayController -up-> GameView
note on link : getAction()

RandomMovementController --> ErrorView
note on link : showError()

RandomMovementController --> Game
note on link: moveFromWasteToTableau(nPlie)\n\
moveFromTableauToTableau(sPile, sCard, dPile)\n\
moveFromTableauToFoundation(sPile, sCard)\n\
moveFromFoundationToTableau(sFoundation, dPile)

@enduml