@startuml UCAnalysis_MoveFromWasteToFoundation

mix_actor Player

package views {
    class MenuView
    class GameCompleteView
    class ErrorView
    class GameView
    class BoardView

    GameView *--> BoardView
    note on link: showBoard()

    GameView *--> MenuView
}

Player -down-> GameView
note on link: Select action

package controllers {
    class PlayController
    class MoveFromWasteToFoundation
    PlayController *-right-> MoveFromWasteToFoundation
}

package models {
    class Game
    class Card
    class Waste
    class Foundation
    Waste ..> Card
    Foundation ..> Card
    Game *-->Waste
    Game *-->Foundation
}

PlayController --> GameView
note on link: readAction()

MoveFromWasteToFoundation --> ErrorView
note on link: showError()

MoveFromWasteToFoundation --> GameView
note on link: showBoard()

MoveFromWasteToFoundation -down-> Game
note on link: *MoveFromWasteToFoundation()\n\
*isFoundationComplete()

MoveFromWasteToFoundation --> GameCompleteView 
note on link: showWinner()

@enduml