@startuml UCAnalysis ReStartGame

mix_actor Player

package views {
  class GameView
  class MenuView
  class ConfirmationView
  GameView --> MenuView
}

Player -right-> GameView
note on link: Select action

package controllers{
    class PlayController
    class RestartGameController
    class StartGameController
    PlayController -right-> RestartGameController
}

package models{
  class Game
}

RestartGameController --> ConfirmationView : confirm()
RestartGameController -right-> StartGameController
StartGameController --> Game : new()

PlayController --> GameView
note on link: readAction

@enduml